services:
  uukv3n8eix:
    container_name: uukv3n8eix_app
    image: ghcr.io/mr-devloper005/upgreeno.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3273:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
